### ISSUE TITLE
Check mod.zip file structure

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#11]
Check if the file structure of a mods zip file is correct:

> Structure
> Mod ZIPs should have the structure shown below. The name of the ZIP is arbitrary.
> 
> ```
> yourmod.zip
> ├───.import
> └───mods-unpacked
>     └───Author-ModName
>         ├───ModMain.gd
>         └───_meta.json
> ```

**Comment by ithinkandicode** [comment]
It's a great idea in theory, but in practise would cause slowdown before the game loads. There's already an unavoidable delay when using mods, but adding further delays to account for potential mistakes made by mod developers might not be the most end-user-focused approach.

Poorly structured mods likely won't load anyway, and if they're close to the structure, we already have some stuff (eg. the required files check) to account for minor errors.

Building an external validator tool might be a good idea though, you could even bundle in your mod imports code to help creators package their mods, maybe with a meta.json editor too. 

You could even use something like gdunzip to check an existing zip's paths, for diagnosing issues either as a mod creator or a mod end-user. The performance penalty for gdunzip wouldn't be noticeable if you're just running it on a single ZIP in an isolated case.

**Comment by ithinkandicode** [comment]
@KANAjetzt  Actually, we might be able to add some validation *after* a ZIP has been loaded, when we loop over `res://mods-unpacked` in `_setup_mods`. That'd save us needing to get the ZIP's contents etc prior to the load.

If we do it in `_setup_mods`, we could check if any folders other than `.import` and `mods-unpacked` are present. And we can stop badly formed mods from loading at this point, since the `_setup_mods` func is what triggers `_init_mod_data`.

It happens before the *manifest.json* stuff so we won't be able to tell if the named mod folder within `res://mods-unpacked` is correct. But we could check to ensure there's only a single folder there.

**Comment by ithinkandicode** [comment]
I don't know how much of an impact this would have on performance though, as we'd be looping over quite a few directories

**Comment by ithinkandicode** [comment]
Closing, I think this has been done
