### ISSUE TITLE
Production and Development Environment Options

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#296]
> René — 20/06/2023 22:03
change #1 res://addons/mod_loader/mod_loader_store.gd
I don't need the options.tres, but want two option profiles: one for development, one for release. Release should be automatically used, so i can't forget to switch it out
>
> ```gdscript
>  func _update_ml_options_from_options_resource() -> void:
>     if OS.has_feature("editor"):
>         var current_options: Resource = preload("res://addons/mod_loader/options/profiles/current.tres")
>         for key in ml_options:
>             ml_options[key] = current_options[key]
>     else:
>         var current_options: Resource = preload("res://addons/mod_loader/options/profiles/production_workshop.tres")
>         for key in ml_options:
>             ml_options[key] = current_options[key]
> ```

### Todos:
- [ ] Implement Feature Flags 

https://github.com/GodotModding/godot-mod-loader/issues/296#issuecomment-1618372594
> some games have different export targets (Dome Keeper: Steam, GOG). To support different options for that case, I think we need the full feature tag system, since we can't predict this. In this case, the gog tag would apply a options file with steam workshop disabled. https://docs.godotengine.org/en/3.5/tutorials/export/feature_tags.html#custom-features

**Comment by ithinkandicode** [comment]
I think the issue there is that we'd be forcing people to use ML Options in a very specific way, replacing the choice to use any number of ML Options profiles down to just 2. It's worth keeping in mind that the ML Options system is set up to be flexible and account for all types of users, ie. both modders and developers. Forcing one profile for the editor and one for release removes that flexibility, especially for modders, who would only be able to use the editor profile.

Personally as a modder, I find it very useful to be able to use different profiles with ML Options, because it lets me keep all my mods in a single project, but lets me swap between different profiles that selectively disable groups of mods at once. If there was only a single editor profile, I'd need to keep editing my `disabled_mods` array whenever I need to change my project focus, rather than being able to just drag and drop my pre-defined profiles.

That said: We **could** split *options.tres* into `options_editor` and `options_production`, which would work similarly to KANA's code example above. That way, we keep the flexibility of being able to use multiple options profiles, while also catering to developers who can just set their production profile once and then forget about it.

**Comment by Qubus0** [comment]
that is rene's example.
i'd work more on a fallback basis - have one profile as default and then one or multiple levels of overrides that take precedence if they are set, similar to how you can define project settings based on feature flags by adding `<option key>.<feature flag>` to your settings. ex: `display/window/size/mode` and `display/window/size/mode.editor`

to allow an "infinite" amount, we'd have to use a Dictionary[String, Resource]. then everyone could just add their flags there and the options would apply when they are met.

**Comment by ithinkandicode** [comment]
Mockup of editor and production options. So it has all the same features as now but satisfies the original request too \o/

![image](https://github.com/GodotModding/godot-mod-loader/assets/43499897/7fe37edb-6fa8-412e-8c84-a00e5186b885)

**Comment by KANAjetzt** [comment]
Adding the Discord Chat here:

> KANA — Today at 14:13
I can't quite picture how this works. How are options defined like this? And how are the options differentiated between feature flags? Would that require a completely new system?

> Ste — Today at 14:20
I would take the existing system to define the default. And additionally add something options_overrides - a dictionary. The dictionary would have a string key, matching one of the feature tags and the value would be a options resource 
this needs to be documeted since dictionary typing is nonexistant
then we'd loop through the dictionary, checking OS.has_feature(override_key). And if it's true, just apply the options and return. if none of those match, apply the default
one issue might be with flags that can be applied simultaneously, like "windows" and "standalone" - but I think the rule would be to avoid that. it doesn't make much sense anyway
I think the most commone tags to eb checked would be these
>
> ```
> debug - Running on a debug build (including the editor)
> release - Running on a release build
> editor - Running on an editor build
> standalone - Running on a non-editor build
> web - Host OS is a Web browser
> ```
>
> does this make sense?

> KANA — Today at 14:30
yep - I think I get it now. 
Sounds like a solid system how likely are tags other then standalone and editor/debug?
Maybe we can start with something like this and expand to your proposal if we see the need?

> Ste — Today at 14:33
yep. but also debug, as i imagine that might be helpful for release builds that go into QA
and i would match the names to the flags
editor, debug, standalone (or release? i don't see much of a difference between the two)

> KANA — Today at 14:39
> Ok so we add:
>
> - options_debug
> - options_editor
> - options_release
>
> And if we receive a request for more, we can implement your feature flag proposal?

**Comment by Qubus0** [comment]
some games have different export targets (Dome Keeper: Steam, GOG). To support different options for that case, I think we need the full feature tag system, since we can't predict this. 
In this case, the gog tag would apply a options file with steam workshop disabled.
https://docs.godotengine.org/en/3.5/tutorials/export/feature_tags.html#custom-features
