### ISSUE TITLE
4.x suport

### ISSUE THREAD

**Issue by A-Boring-Square** [GodotModding/godot-mod-loader#419]
For a game that my team and I are creating, our community has asked for mod support. Since we use Godot 4.x for our games, it would be much appreciated if you could port this excellent library to Godot 4.x.

**Comment by Qubus0** [comment]
you can check the current version in the [4.x branch](https://github.com/GodotModding/godot-mod-loader/tree/4.x), which works completely fine if you don't use `class_name`, like windowkill, otherwise you can check here for what issues remain
- https://github.com/GodotModding/godot-mod-loader/issues/315

we're currently implementing workarounds which do work, but need to be cleaned up before merging. these are going to be tested in dome keeper pretty soon.
- https://github.com/GodotModding/godot-mod-loader/pull/408
