### ISSUE TITLE
Check for duplicate mod ids

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#5]
> *I just remembered that you will have to check for duplicate mod IDs since those are just user-made[*](https://discord.com/channels/1028191864966361178/1028381928275058838/1056907018583154780)
> 
> 
> [*https://discord.com/channels/1028191864966361178/1028381928275058838/1056907018583154780*](https://discord.com/channels/1028191864966361178/1028381928275058838/1056907018583154780)
>

- Maybe we can also add something generated, after the user based ID, to prevent duplicate IDs.

**Comment by KANAjetzt** [comment]
I think we are fine just throwing an error when a mod with the same Id is detected and not loading them or the second one 👐

> Blade — Today at 19:17
> Question here is whether we refuse both or only the second one to register with the same namespace. I would say both. This would require mods to only be fully loaded after all mods have been validated, but this way we avoid potential corruption issues

> Ste — Today at 19:18
> yes i agree to refusing both. user has to resolve that, nothing we can decide

**Comment by ithinkandicode** [comment]
Closing this because I don't think we need to do anything here. ML has validation that means your folder name must your  `{author}-{name}`, so you can't make two mods with the same `name`, so we'll never have duplicate IDs:

![image](https://user-images.githubusercontent.com/43499897/216729094-95997b12-bf28-4cf2-a72f-c6124c3d1f5f.png)

And if another mod uses the same `name` as yours, as their `author` will be different, so their mod ID will be different too.
